apiVersion: v1
kind: Service
metadata:
  name: processing-service
  labels:
    app: processing
spec:
  selector:
    app: processing
  ports:
    - name: http
      port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: processing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /processing/(.*)
          backend:
            serviceName: processing-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
  labels:
    app: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
      - name: processing
        image: JSVAR_DOCKERIMAGE
