apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucprocessing
  labels:
    app: ucprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucprocessing
  template:
    metadata:
      labels:
        app: ucprocessing
    spec:
      containers:
      - name: ucprocessing
        image: JSVAR_DOCKERIMAGE
---
apiVersion: v1
kind: Service
metadata:
  name: ucprocessing-service
spec:
  type: NodePort
  selector:
    app: ucprocessing
  ports:
  - protocol: TCP
    port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucprocessing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /ucprocessing/(.*)
          backend:
            serviceName: ucprocessing-service
            servicePort: 80
